#! /usr/bin/python

import os

## dependency check
##
##



cwd=os.getcwd()
os.chdir(cwd+"/python")
os.system("python setup.py build")
os.system("python setup.py install")
os.chdir(cwd+"/src")
os.system("make")
